NongSanZeno/Controllers/LoginUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;
using NongSanZeno.Models;

namespace NongSanZeno.Controllers
{
    public class LoginUserController : Controller
    {
        // create string MD5
        public static string MD5Hash(string input)
        {
            StringBuilder hash = new StringBuilder();
            MD5CryptoServiceProvider md5provider = new MD5CryptoServiceProvider();
            byte[] bytes = md5provider.ComputeHash(new UTF8Encoding().GetBytes(input));

            for (int i = 0; i < bytes.Length; i++)
            {
                hash.Append(bytes[i].ToString("x2"));
            }
            return hash.ToString();
        }


        dbNongSanZenoDataContext data = new dbNongSanZenoDataContext();
        // GET: LoginUser
        [HttpGet]
        public ActionResult DangKy()
        {
            return View();
        }

        //post: ham dang ky(post) nhap du lieu tu trang dangky
        //va thuc hien viec tao moi du lieu
        [HttpPost]
        public ActionResult DangKy(FormCollection collection, tbKhachHang kh)
        {
            var hoten = collection["Hoten"];
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            var matkhaunhaplai = collection["Nhaplaimatkhau"];
            var diachi = collection["Diachi"];
            var email = collection["Email"];
            var dienthoai = collection["Dienthoai"];
            var ngaysinh = String.Format("{0:MM/dd/yyyy}", collection["Ngaysinh"]);

            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống*";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập*";
            }
            else if (String.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu*";
            }
            else if (String.IsNullOrEmpty(matkhaunhaplai))
            {
                ViewData["Loi4"] = "Phải nhập lại mật khẩu*";
            }
            if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi6"] = "Email không được bỏ trống*";
            }
            if (String.IsNullOrEmpty(dienthoai))
            {
                ViewData["Loi7"] = "Phải nhập số điện thoại*";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (KH)
                kh.TenKH = hoten;
                kh.TaiKhoan = tendn;
                kh.MatKhau = MD5Hash(matkhau);
                kh.Email = email;
                kh.DiaChiKH = diachi;
                kh.DienThoaiKH = dienthoai;
                kh.NgaySinh = DateTime.Parse(ngaysinh);
                data.tbKhachHangs.InsertOnSubmit(kh);
                data.SubmitChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.DangKy();
        }

        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }

        public ActionResult Dangnhap(FormCollection collection)
        {
            //Gan cac gia tri nguoi dung nhap lieu cho cac bien
            var tendn = collection["TenDN"];
            var matkhau = collection["Matkhau"];
            if (string.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đang nhập*";
            }
            else if (string.IsNullOrEmpty(matkhau))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu*";
            }
            else
            {
                //Gán giá trị cho đối tượng được tạo mới (KH)
                tbKhachHang kh = data.tbKhachHangs.SingleOrDefault(n => n.TaiKhoan == tendn && n.MatKhau == MD5Hash(matkhau));
                if (kh != null)
                {
                    Session["User"] = kh.TenKH;
                    Session["Taikhoan"] = kh;

                    return RedirectToAction("SanPham", "NongSanZeno");
                }
                else
                {
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng";
                }
            }
            return View();
        }

        public ActionResult Dangxuat()
        {
            Session["User"] = null;
            Session["Taikhoan"] = null;
            return RedirectToAction("SanPham", "NongSanZeno");
        }
    }
}

NongSanZeno/Views/LoginUser/DangKy.cshtml
@{
    ViewBag.Title = "DangKy";
    Layout = "~/Views/Layout/_LayoutLoginUser.cshtml";
}

<form action="#" method="post">
    <div class="form-group first">
        <label for="user">Họ và tên</label>
        <input style="height:45px; border-radius:24px" type="text" class="form-control" placeholder="tên của bạn" name="Hoten">
        <h6 style="color:red; text-align:center">@ViewData["Loi1"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Tên đăng nhập</label>
        <input style="height:45px; border-radius:24px" type="text" class="form-control" placeholder="tên đăng nhập" name="TenDN">
        <h6 style="color:red; text-align:center">@ViewData["Loi2"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Mật khẩu</label>
        <input style="height:45px; border-radius:24px" type="password" class="form-control" placeholder="mật khẩu" name="Matkhau">
        <h6 style="color:red; text-align:center">@ViewData["Loi3"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Nhập lại mật khẩu</label>
        <input style="height:45px; border-radius:24px" type="password" class="form-control" placeholder="nhập lại mật khẩu" name="Nhaplaimatkhau">
        <h6 style="color:red; text-align:center">@ViewData["Loi4"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Địa chỉ</label>
        <input style="height:45px; border-radius:24px" type="text" class="form-control" placeholder="địa chỉ" name="Diachi">
        <h6 style="color:red; text-align:center">@ViewData["Loi5"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Email</label>
        <input style="height:45px; border-radius:24px" type="text" class="form-control" placeholder="email@gmail.com" name="Email">
        <h6 style="color:red; text-align:center">@ViewData["Loi6"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Điện thoại</label>
        <input style="height:45px; border-radius:24px" type="text" class="form-control" placeholder="điện thoại" name="Dienthoai">
        <h6 style="color:red; text-align:center">@ViewData["Loi7"]</h6>
    </div>
    <div class="form-group first">
        <label for="user">Ngày sinh</label>
        <input style="height:45px; border-radius:24px" type="date" class="form-control" placeholder="ngày sinh" name="Ngaysinh">
    </div>

    <input type="submit" value="Đăng Ký" class="btn btn-block py-2 btn-primary">
</form>
<p>
    @Html.ActionLink("Bạn đã có tài khoản? Đăng nhập", "Dangnhap", "LoginUser")
</p>

NongSanZeno/Views/LoginUser/Dangnhap.cshtml
@{
    ViewBag.Title = "Dangnhap";
    Layout = "~/Views/Layout/_LayoutLoginUser.cshtml";
}


<div class="text-center mb-5">
    <h3 class="text-uppercase">ĐĂNG NHẬP</h3>
</div>
<form action="#" method="post">
    <div class="form-group first">
        <label for="username">Tên đăng nhập</label>
        <input style="height:45px; border-radius:24px" type="text" class="form-control" placeholder="Tên đăng nhập" name="TenDN">
        <h6 style="color:red; text-align:center">@ViewData["Loi1"]</h6>
    </div>
    <div class="form-group last mb-3">
        <label for="password">Mật khẩu</label>
        <input style="height:45px; border-radius:24px" type="password" class="form-control" placeholder="Mật khẩu" name="Matkhau">
        <h6 style="color:red; text-align:center">@ViewData["Loi2"]</h6>
    </div>

    <div class="d-sm-flex mb-5 align-items-center">
        <label class="control control--checkbox mb-3 mb-sm-0">
            <span class="caption">Remember me</span>
            <input type="checkbox" checked="checked" />
            <div class="control__indicator"></div>
        </label>
        <span class="ml-auto"><a href="#" class="forgot-pass">Forgot Password</a></span>
    </div>

    <input type="submit" value="Đăng nhập" class="btn btn-block py-2 btn-primary">
</form>

<p>
    @Html.ActionLink("Bạn chưa có tài khoản? Đăng ký", "Dangky", "LoginUser")
</p>
<p>
    @Html.ActionLink("Quay lại trang chủ", "TrangChu", "Home")
</p>

NongSanZeno/Views/LoginUser/Thongtintk.cshtml
@model NongSanZeno.Models.tbKhachHang
@{
    ViewBag.Title = "Thongtintk";
    Layout = "~/Views/Layout/_LayoutUser.cshtml";
}
<div class="text-center mb-5">
    <h3 class="text-uppercase">THÔNG TIN CỦA BẠN</h3>
</div>
<form action="#" method="post">
    <div class="form-group first">
        <label>
            Tên khách hàng: @Html.DisplayFor(model => model.TenKH)
        </label>
        <label>
            Tên Đăng Nhập: @Html.DisplayFor(model => model.TaiKhoan)
        </label>
        <label>
            Email: @Html.DisplayFor(model => model.Email)
        </label>
        <br />
        <label>
            Số điện thoại: @Html.DisplayFor(model => model.DienThoaiKH)
        </label>
        <br />
        <label>
            Dịa Chỉ: @Html.DisplayFor(model => model.DiaChiKH)
        </label>
    </div>

    <div>
        <input type="submit" value="Chỉnh sửa thông tin" class="btn btn-block py-2 btn-primary">
    </div>
</form>