NongSanZeno/Controllers/AdminDonHangController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using NongSanZeno.Models;
using PagedList;
using System.Configuration;
using System.Data.SqlClient;

namespace NongSanZeno.Controllers
{
    public class AdminDonHangController : Controller
    {
        dbNongSanZenoDataContext data = new dbNongSanZenoDataContext();

        public string ReturnDateForDisplay
        {
            get
            {
                return this.ReturnDateForDisplay.ToString();
            }
        }

        // GET: AdminDonHang
        //--------------------------- Đơn Đặt Hàng ----------------------------------
        [HttpGet]
        public ActionResult DSdonhang(int? page)
        {
            int pagesize = 8;
            int pageNum = (page ?? 1);
            var GioHienTai = DateTime.Today;
            var list = data.tbDonHangs.Where(s => s.NgayDat >= GioHienTai).OrderByDescending(i => i.NgayDat).ToList();
            return View(list.ToPagedList(pageNum, pagesize));
        }
        [HttpPost]
        public ActionResult DSdonhang(string date, string date2, int? page)
        {
            int pagesize = 8;
            int pageNum = (page ?? 1);
            var Date = DateTime.Parse(date);

            if (date2 == "")
            {
                var listdate = data.tbDonHangs.Where(s => s.NgayDat >= Date).OrderByDescending(i => i.NgayDat).ToList();
                return View(listdate.ToPagedList(pageNum, pagesize));
            }
            var Date2 = DateTime.Parse(date2);
            var list = data.tbDonHangs.Where(s => s.NgayDat >= Date && s.NgayDat <= Date2).OrderByDescending(i => i.NgayDat).ToList();
            return View(list.ToPagedList(pageNum, pagesize));
        }

        public ActionResult ChiTietdonhang(int? id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            if (id == null)
            {
                return HttpNotFound();
            }
            var list = data.tbChiTietDonHangs.Where(s => s.MaDH == id).OrderByDescending(s => s.MaSP).ToList();
            return View(list);
        }

        [HttpGet]
        public ActionResult Suadonhang(int id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            
            tbDonHang dh = data.tbDonHangs.SingleOrDefault(n => n.MaDH == id);
            ViewBag.TTDH = new SelectList(data.tbTinhTrangDHs.ToList().OrderBy(n => n.MaTTDH), "MaTTDH", "TenTTDH", dh.MaTTDH);
            if (dh == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            return View(dh);
        }

        [HttpPost, ActionName("Suadonhang")]
        public ActionResult XacNhanSuadonhang(int id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            else
            {
                tbDonHang dh = data.tbDonHangs.SingleOrDefault(n => n.MaDH == id);
                if (dh == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                UpdateModel(dh);
                data.SubmitChanges();
                return RedirectToAction("DSdonhang");
            }
        }
        public List<tbChiTietDonHang> LayChiTietdonhang()
        {
            List<tbChiTietDonHang> list = Session["chitietdonhang"] as List<tbChiTietDonHang>;
            if (list == null)
            {
                list = new List<tbChiTietDonHang>();
                Session["chitietdonhang"] = list;
            }
            return list;
        }

        public ActionResult XoaTatCaChiTiet()
        {
            List<tbChiTietDonHang> list = LayChiTietdonhang();
            list.Clear();
            return RedirectToAction("DonDatHang");
        }
        public ActionResult XoaChiTietdonhang(int id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            else
            {
                tbChiTietDonHang ctdh = data.tbChiTietDonHangs.Where(n => n.MaDH == id).FirstOrDefault();
                ViewBag.MaDonHang = ctdh.MaDH;
                if (ctdh == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                return View(ctdh);
            }
        }
        [HttpPost, ActionName("XoaChiTietdonhang")]
        public ActionResult XacNhanXoaChiTietdonhang(int id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            else
            {
                tbChiTietDonHang ctdh = data.tbChiTietDonHangs.Where(n => n.MaDH == id).FirstOrDefault();

                ViewBag.MaDonHang = ctdh.MaDH;
                if (ctdh == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                data.tbChiTietDonHangs.DeleteOnSubmit(ctdh);
                data.SubmitChanges();
                return RedirectToAction("DSdonhang", "AdminHoaDon");
            }
        }
        public ActionResult Xoadonhang(int id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            else
            {
                tbDonHang dh = data.tbDonHangs.Where(n => n.MaDH == id).FirstOrDefault();
                // DONDATHANG ncc = context.DONDATHANGs.SingleOrDefault(n => n.MaDonHang == id);
                ViewBag.MaDonHang = dh.MaDH;
                if (dh == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                return View(dh);
            }
        }
        [HttpPost, ActionName("Xoadonhang")]
        public ActionResult XacNhanXoadonhang(int id)
        {
            if (Session["TKadmin"] == null)
            {
                return RedirectToAction("SanPham", "NongSanZeno");
            }
            else
            {
                tbDonHang dh = data.tbDonHangs.Where(n => n.MaDH == id).FirstOrDefault();

                ViewBag.MaDH = dh.MaDH;
                if (dh == null)
                {
                    Response.StatusCode = 404;
                    return null;
                }
                data.tbDonHangs.DeleteOnSubmit(dh);
                data.SubmitChanges();
                return RedirectToAction("DSdonhang");
            }
        }
    }
}

NongSanZeno/Views/AdminDonHang/ChiTietdonhang.cshtml
@model IEnumerable<NongSanZeno.Models.tbChiTietDonHang>

@{
    ViewBag.Title = "ChiTietdonhang";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<table class="table">
    <tr style="text-align:center">
        <th>
            @Html.DisplayName("Mã Đơn Hàng")
        </th>
        <th>
            @Html.DisplayName("Mã Sản Phảm")
        </th>
        <th>
            @Html.DisplayName("Tên Sản Phẩm")
        </th>
        <th>
            @Html.DisplayName("Ảnh")
        </th>
        <th>
            @Html.DisplayName("Số Lượng")
        </th>
        <th>
            @Html.DisplayName("Đơn Giá")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr style="text-align:center">
            <td>
                @Html.DisplayFor(modelItem => item.tbDonHang.MaDH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tbSanPham.MaSP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.tbSanPham.TenSP)
            </td>
            <td>
                <img src="~/images/sanpham/@Html.DisplayFor(modelItem => item.tbSanPham.AnhSP)" alt="Alternate Text" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SoLuong)
            </td>
            <td>
                ₫@String.Format("{0:0,0 }", item.DonGia)
            </td>
            <td>
                @*<a href="@Url.Action("XoaChiTietdonhang","AdminDonHang", new { id = item.MaDH })">Xoá</a>*@
                @Html.ActionLink("Xóa", "XoaChiTietdonhang", new { id = item.MaDH }, new { @class = "btn btn-success" })
            </td>
        </tr>
    }

</table>
<div class="space" style="display:flex;justify-content:space-around">
    <a class="return" href="@Url.Action("DSdonhang","AdminDonHang")">TRỞ VỀ</a>
</div>

<style>
    .btn-success {
        color: #fff;
        background-color: #006400;
        border-color: #006400;
    }
    table {
        width: 100%;
        margin-bottom: 50px;
    }

    th {
        height: 50px;
        background: #fbffdf;
        color: black;
        text-transform: uppercase;
    }

    td {
        text-align: center;
    }

    th, td {
        padding-left: 20px;
        padding-right: 10px;
        padding-top: 15px;
        padding-bottom: 20px;
    }

    img {
        width: 100px;
        height: 100px;
        margin-right: -100px;
    }

    tr {
        color: #777;
        font-weight: bold;
    }

        tr:hover {
            background-color: #777;
            transition: 0.5s ease all;
            color: white;
        }

    .return {
        color: white;
        background: #4e4e22;
        border: none;
        outline: none;
        padding: 1% 5% 1% 5%;
        font-size: 1em;
        cursor: pointer;
        letter-spacing: 1px;
        font-weight: bold;
        font-family: 'Open Sans', sans-serif;
        transition: 0.5s all;
        -webkit-transition: 0.5s all;
        -o-transition: 0.5s all;
        -moz-transition: 0.5s all;
        -ms-transition: 0.5s all;
        border-radius: 30px;
    }

        .return:hover {
            color: white;
            background: #958d5b;
        }

    @@media(max-width: 1024px) {
        img {
            width: 250px;
            height: 150px;
        }

        .return {
            margin-left: 32%;
        }
    }

    @@media(max-width: 780px) {
        th, td {
            padding-left: 20px;
            padding-right: 0px;
        }

        img {
            width: 250px;
            height: 150px;
        }

        .return {
            margin-left: 30%;
        }
    }

    @@media(max-width: 430px) {
        table {
            font-size: 12px;
        }

        th, td {
            padding-left: 20px;
            padding-right: 10px;
        }

        img {
            width: 150px;
            height: 100px;
        }

        .return {
            margin-left: 20%;
        }
    }

    @@media(max-width: 380px) {
        table {
            font-size: 10px;
        }

        th, td {
            padding-left: 10px;
            padding-right: 20px;
        }

        img {
            width: 100px;
            height: 80px;
        }

        .return {
            margin-left: 15%;
        }
    }

    @@media(max-width: 320px) {
        table {
            font-size: 8px;
        }

        th, td {
            padding-left: 0px;
            padding-right: 0px;
        }

        .return {
            font-size: 14px;
            margin-left: 8%;
        }
    }
</style>

NongSanZeno/Views/AdminDonHang/DSdonhang.cshtml
@using NongSanZeno.Models
@using PagedList.Mvc;
@model PagedList.PagedList<tbDonHang>

@{
    ViewBag.Title = "DSdonhang";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

@using (Html.BeginForm())
{
    <input style="color:black" type="date" required name="date" />
    <input style="text-align: center; color: black; background-color: #958d5b" type="submit" value="Tìm" class="btn btn-default" />
    <input style="color:black;float:right" type="date" name="date2" />
}
<table class="table" border="1">
    <tr>
        <th>
            @Html.DisplayName("Tên Khách Hàng")
        </th>
        <th>
            @Html.DisplayName("Số điện thoại")
        </th>
        <th>
            @Html.DisplayName("Địa chỉ")
        </th>
        <th>
            @Html.DisplayName("Ghi chú")
        </th>
        <th>
            @Html.DisplayName("Ngày Đặt")
        </th>
        <th>
            @Html.DisplayName("Ngày Giao")
        </th>
        <th>
            @Html.DisplayName("Tình Trạng Giao Hàng")
        </th>
        <th>
            @Html.DisplayName("Tổng tiền")
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.tbKhachHang.TenKH)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SDT)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DiaChi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GhiChu)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.NgayDat)
            </td>
            <td>
                @String.Format("{0:dd/MM/yyyy}", item.NgayGiao)
            </td>
            <td style="color: black">
                @Html.DisplayFor(modelItem => item.tbTinhTrangDH.TenTTDH)
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.TongTien)*@
                ₫@String.Format("{0:0,0 }", item.TongTien)
            </td>
            @*<td class="tool">
                <a href="@Url.Action("ChiTietdonhang", "AdminDonHang", new { id = item.MaDH })">Chi tiết</a> |
                <a href="@Url.Action("Suadonhang", "AdminDonHang", new { id = item.MaDH })">Sửa</a> |
                <a href="@Url.Action("Xoadonhang", "AdminDonHang", new { id = item.MaDH })">Xoá</a>
            </td>*@
            <td>
                @Html.ActionLink("Chi tiết", "ChiTietdonhang", new { id = item.MaDH }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Sửa", "Suadonhang", new { id = item.MaDH }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Xoá", "Xoadonhang", new { id = item.MaDH }, new { @class = "btn btn-success" })
            </td>
        </tr>
    }
</table>

@*Tao lien ket cac trang*@
<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("DSdonhang", new { page = page }))
</div>
<style>
    .btn-success {
        color: #fff;
        background-color: #006400;
        border-color: #006400;
    }

    form {
        margin: 20px 20px 50px 20px;
    }

    input[type="date"] {
        border-radius: 10px;
        padding: 10px 10px;
    }

    input[type="submit"] {
        margin-left: 25%;
        width: 200px;
        color: white;
        background: #ea2858;
        border: none;
        padding: .7em 20px;
        outline: none;
        font-size: 1em;
        cursor: pointer;
        letter-spacing: 1px;
        font-weight: 400;
        font-family: 'Open Sans', sans-serif;
        transition: 0.5s all;
        -webkit-transition: 0.5s all;
        -o-transition: 0.5s all;
        -moz-transition: 0.5s all;
        -ms-transition: 0.5s all;
        border-radius: 30px;
    }

    form input[type="submit"]:hover {
        background: #fff;
        color: black;
        transition: 0.5s all;
        -webkit-transition: 0.5s all;
        -o-transition: 0.5s all;
        -moz-transition: 0.5s all;
        -ms-transition: 0.5s all;
    }

    .pagination {
        position: relative;
        background: #fff;
        display: flex;
        padding: 10px 20px;
        border-radius: 50px;
        box-shadow: 0 5px 15px rgba(0,0,0,.2);
        text-align: center;
        justify-content: center
    }

        .pagination > li {
            margin: 0 5px;
            width: 50px;
            height: 50px;
            line-height: 50px;
            text-align: center;
        }

            .pagination > li > a {
                color: #777;
                font-weight: 600;
                border-radius: 50%;
                display: block;
            }

            .pagination > li:hover a,
            .pagination > li.active a {
                background: #333;
                color: #fff
            }


    .tool > a:hover {
        text-decoration: underline;
    }

    .page {
        text-align: center;
        justify-content: center;
        display: inline;
    }

    table {
        width: 100%;
    }

    th {
        height: 50px;
        background: #fbffdf;
        color: black;
        text-transform: uppercase;
    }

    td {
        text-align: center;
    }

    th, td {
        padding-left: 20px;
        padding-right: 10px;
        padding-top: 15px;
        padding-bottom: 20px;
    }

    tr {
        color: #777;
        font-weight: bold;
    }

        tr:hover {
            background-color: #777;
            transition: 0.5s ease all;
            color: white;
        }


    @@media(max-width:1024px) {
        table {
            font-size: 10px;
        }

        form {
            margin-bottom: 50px;
        }

        input[type="date"] {
            width: 100%;
            font-size: 12px;
        }

        input[type="submit"] {
            margin-left: 35%;
            margin-top: 10px;
            margin-bottom: 10px;
            width: 200px;
        }

        th, td {
            padding-right: 0px;
            padding-left: 10px;
        }
    }

    @@media(max-width: 768px) {
        form {
            margin-bottom: 50px;
        }

        table {
            font-size: 9px;
        }

        input[type="submit"] {
            margin-left: 32%;
        }

        th, td {
            padding-right: 0px;
            padding-left: 5px;
        }
    }

    @@media(max-width: 430px) {
        form {
            margin-bottom: 50px;
        }

        table {
            font-size: 10px;
        }

        input[type="submit"] {
            margin-left: 25%;
        }

        th, td {
            padding-right: 0px;
            padding-left: 5px;
        }

        .pagination {
            width: 95%;
            padding: 5px 20px;
            margin-left: 15px;
        }
    }

    @@media(max-width: 380px) {
        form {
            margin-bottom: 50px;
        }

        table {
            font-size: 9px;
        }

        input[type="submit"] {
            margin-left: 20%;
        }
    }

    @@media(max-width: 320px) {
        form {
            margin-bottom: 50px;
        }

        input[type="date"] {
            width: 100%;
            font-size: 12px;
        }

        input[type="submit"] {
            margin-left: 25%;
            margin-top: 10px;
            margin-bottom: 10px;
            width: 150px;
        }

        table {
            font-size: 8px;
        }

        .tri-state.list-box {
            color: black;
        }

        .pagination {
            width: 95%;
            padding: 5px 20px;
            margin-left: 15px;
            font-size: 10px;
        }
    }
</style>

NongSanZeno/Views/AdminDonHang/Suadonhang.cshtml
@model NongSanZeno.Models.tbDonHang

@{
    ViewBag.Title = "Suadonhang";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="~/Content/Admin/admin.css">

<hr />
<h2 style="font-size: 26px; text-align: center;">Điều Chỉnh Thông Tin Đơn Hàng</h2>
<hr />

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.MaDH)

        <div class="form-group">
            Số Điện Thoại
            <div class="col-md-10">
                <input required type="text" name="TenSP" value="@Model.SDT" />
            </div>
        </div>

        <div class="form-group">
            Địa Chỉ
            <div class="col-md-10">
                <input required type="text" name="DiaChi" value="@Model.DiaChi" />
            </div>
        </div>

        <div class="form-group">
            Ghi Chú
            <div class="col-md-10">
                <textarea required name="GhiChu" rows="10" cols="40">@Model.GhiChu</textarea>
            </div>
        </div>

        <div class="form-group">
            Tổng Tiền
            <div class="col-md-10">
                <input required type="text" name="TongTien" value="@Model.TongTien" />
            </div>
        </div>
        <div class="form-group">
            Ngày Đặt
            <div class="col-md-10">
                <p style="color:black">@String.Format("{0:dd/MM/yyyy}", Model.NgayDat)</p>              
            </div>
        </div>
        <div class="form-group">
            Ngày Giao
            <div class="col-md-10">
                <p style="color:black">@String.Format("{0:dd/MM/yyyy}", Model.NgayGiao)</p>
                <input required type="date" name="NgayGiao" value="@Model.NgayGiao" />
            </div>
        </div>
        <div class="form-group">
            Tình Trạng Đơn Hàng
            <div class="col-md-10">
                @Html.DropDownList("TTDH")
            </div>
        </div>
        @*<div class="form-group">
            @Html.LabelFor(model => model.SDT, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SDT, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SDT, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div><input style="font-weight: bold" type="submit" value="Lưu" class="btn btn-default" /></div>
            <div class="btn btn-default" style="font-weight:bold; color:white"><a href="/AdminDonHang/DSdonhang">Quay Lại</a></div>
        </div>
    </div>
}

<style>
    /*@@media(max-width: 1040px) {
        .return {
            margin-left: 28%;
            padding: 0.7em 135px;
            margin-top: 0px;
            width: 44%;
        }
    }

    @@media(max-width: 780px) {


        .return {
            margin-left: 28%;
            padding: 0.7em 75px;
            margin-top: 0px;
            width: 44%;
        }
    }

    @@media(max-width: 430px) {


        .return {
            margin-left: 28%;
            margin-top: 0px;
            width: 44%;
            padding: 0.7em 55px;
        }
    }

    @@media(max-width: 380px) {
        .return {
            margin-left: 28%;
            margin-top: 0px;
            width: 44%;
            padding: 0.7em 49px;
        }
    }

    @@media(max-width: 320px) {
        .return {
            margin-left: 28%;
            margin-top: 0px;
            width: 45%;
            padding: 0.7em 38px;
        }
    }*/
</style>

NongSanZeno/Views/AdminDonHang/XoaChiTietdonhang.cshtml
@model NongSanZeno.Models.tbChiTietDonHang

@{
    ViewBag.Title = "XoaChiTietdonhang";
    Layout = "~/Views/Layout/_LayoutAdmin.cshtml";
}

<link rel="stylesheet" href="~/Content/Admin/admin.css">

<h3>Bạn chắc chắn muốn xóa chi tiết đơn hàng này ?</h3>
<div>
    <h4>Chi tiết đơn hàng</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Mã đơn hàng: @Html.DisplayFor(model => model.MaDH)
        </dt>

        <dt>
            Mã sản phẩm: @Html.DisplayFor(model => model.MaSP)
        </dt>

        <dt>
            Số lượng: @Html.DisplayFor(model => model.SoLuong)
        </dt>

        <dt>
            Đơn giá: @Html.DisplayFor(model => model.DonGia)
        </dt>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-actions no-color">
            <input type="submit" value="Xóa" class="btn btn-default" />
            <div style="text-align:center"><a class="btn" href="/AdminDonHang/DSdonhang"> Trở về</a></div>
        </div>
    }
</div>

<style>
    .dl-horizontal {
        width: 60%;
        margin-top: 20px;
        margin-left: 20%;
        padding-left: 10%;
        font-size: 20px;
        border: solid 2px;
        box-shadow: 0px 15px 15px 10px #808080;
    }

    dt {
        color: black;
        margin: 20px 10px;
    }

    .form-actions {
        margin-top: 80px;
        margin-left: 18%;
        width: 100%;
    }

    .btn {
        margin-left: 8%;
        color: white;
        background: #4e4e22;
        border: none;
        padding: .7em 20px;
        outline: none;
        width: 20%;
        font-size: 1em;
        cursor: pointer;
        letter-spacing: 1px;
        font-weight: 400;
        font-family: 'Open Sans', sans-serif;
        transition: 0.5s all;
        -webkit-transition: 0.5s all;
        -o-transition: 0.5s all;
        -moz-transition: 0.5s all;
        -ms-transition: 0.5s all;
        border-radius: 30px;
        float: left;
    }

        .btn:hover {
            color: white;
            background: #958d5b;
        }

    @@media(max-width: 1040px) {
        .return {
            margin-left: 8%;
            padding: 0.7em 43px;
            margin-top: 0px;
            width: 20%;
        }
    }

    @@media(max-width: 780px) {
        label {
            margin-left: 22%;
        }

        .btn {
            margin-left: 2%;
            width: 25%;
        }

        .return {
            margin-left: 4%;
            padding: 0.7em 47px;
            margin-top: 0px;
            width: 28%;
        }
    }

    @@media(max-width: 430px) {
        label {
            margin-left: 20%;
        }

        .return {
            margin-left: 5%;
            margin-top: 0px;
            width: 29%;
            padding: 0.7em 25px;
        }
    }

    @@media(max-width: 380px) {
        label {
            margin-left: 18%;
        }

        .btn {
            margin-left: 2%;
            width: 25%;
        }

        .return {
            margin-left: 3%;
            margin-top: 0px;
            width: 31%;
            padding: 0.7em 24px;
        }
    }

    @@media(max-width: 320px) {
        label {
            margin-left: 15%;
        }

        .btn {
            margin-left: 2%;
            width: 30%;
        }

        .return {
            margin-top: 0px;
            width: 30%;
            padding: 0.7em 14px;
        }
</style>